import os
import json
import re
from openai import OpenAI


client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)


def target_word_count(duration: int) -> int:
    """
    Approximate narration word count.

    Normal narration speed is roughly 130–150 words/minute.
    We use approximately 140 WPM.
    """

    if duration <= 30:
        return 70

    if duration <= 45:
        return 105

    return 140


def clean_script(text: str) -> str:
    """
    Remove unwanted formatting from the generated script.
    """

    if not text:
        return ""

    text = text.strip()

    # Remove markdown code fences if the model returns them.
    text = re.sub(
        r"^```(?:json|text)?",
        "",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"```$",
        "",
        text,
        flags=re.IGNORECASE,
    )

    return text.strip()


def generate_script(
    topic: str,
    duration: int = 30,
):
    """
    Generate a video script and dialogue based on the
    requested video duration.

    Returns:

        script_text
        dialogue
    """

    if duration not in (30, 45, 60):
        raise ValueError(
            "Duration must be 30, 45, or 60 seconds."
        )

    words = target_word_count(duration)

    prompt = f"""
Create a high-retention AI video script about:

{topic}

The video MUST be approximately {duration} seconds long.

Target approximately {words} spoken words.

The script should:

- Start with a strong hook.
- Keep the viewer interested.
- Use short, natural sentences.
- Avoid unnecessary introductions.
- Avoid stage directions.
- Avoid camera directions.
- Avoid sound-effect instructions.
- Be suitable for AI voice narration.
- End naturally.
- Do not mention that the script was generated by AI.

Return ONLY valid JSON in this exact format:

{{
    "script": "complete narration script",
    "dialogue": [
        "sentence 1",
        "sentence 2",
        "sentence 3"
    ]
}}
"""

    response = client.chat.completions.create(
        model=os.getenv(
            "OPENAI_SCRIPT_MODEL",
            "gpt-4o-mini",
        ),
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a professional short-form "
                    "video script writer."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        temperature=0.8,
    )

    raw = response.choices[0].message.content

    if not raw:
        raise RuntimeError(
            "The AI returned an empty script."
        )

    raw = clean_script(raw)

    try:
        data = json.loads(raw)

    except json.JSONDecodeError as exc:

        raise RuntimeError(
            "The AI returned invalid script JSON."
        ) from exc

    script_text = str(
        data.get("script", "")
    ).strip()

    dialogue = data.get(
        "dialogue",
        []
    )

    if not script_text:
        raise RuntimeError(
            "No script was generated."
        )

    if not isinstance(
        dialogue,
        list
    ):

        raise RuntimeError(
            "Invalid dialogue format."
        )

    dialogue = [
        str(line).strip()
        for line in dialogue
        if str(line).strip()
    ]

    if not dialogue:
        raise RuntimeError(
            "No dialogue was generated."
        )

    return (
        script_text,
        dialogue,
    )