import os
import json
import re

from openai import OpenAI


# ============================================================
# OPENAI CLIENT
# ============================================================

def get_openai_client():
    """
    Create the OpenAI client only when it is actually needed.

    This prevents the entire FastAPI application from crashing
    during startup when the API key is missing.
    """

    api_key = os.getenv("OPENAI_API_KEY")

    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is not configured on the server. "
            "Add OPENAI_API_KEY to your deployment environment "
            "variables and restart the application."
        )

    return OpenAI(
        api_key=api_key
    )


# ============================================================
# TARGET WORD COUNT
# ============================================================

def target_word_count(duration: int) -> int:
    """
    Approximate narration length.

    30 seconds  -> approximately 70 words
    45 seconds  -> approximately 105 words
    60 seconds  -> approximately 140 words
    """

    if duration == 30:
        return 70

    if duration == 45:
        return 105

    if duration == 60:
        return 140

    raise ValueError(
        "Duration must be 30, 45, or 60 seconds."
    )


# ============================================================
# CLEAN AI RESPONSE
# ============================================================

def clean_response(text: str) -> str:
    """
    Remove Markdown code fences if the model accidentally
    wraps its JSON response in them.
    """

    if not text:
        return ""

    text = text.strip()

    text = re.sub(
        r"^```(?:json|text)?",
        "",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"```$",
        "",
        text,
        flags=re.IGNORECASE,
    )

    return text.strip()


# ============================================================
# GENERATE SCRIPT
# ============================================================

def generate_script(
    topic: str,
    duration: int = 30,
):
    """
    Generate a video script appropriate for the requested
    video duration.

    Returns:

        script_text
        dialogue
    """

    # --------------------------------------------------------
    # VALIDATE DURATION
    # --------------------------------------------------------

    if duration not in (30, 45, 60):
        raise ValueError(
            "Duration must be 30, 45, or 60 seconds."
        )

    # --------------------------------------------------------
    # DETERMINE APPROXIMATE SCRIPT LENGTH
    # --------------------------------------------------------

    word_count = target_word_count(
        duration
    )

    # --------------------------------------------------------
    # GET OPENAI CLIENT
    # --------------------------------------------------------

    client = get_openai_client()

    # --------------------------------------------------------
    # PROMPT
    # --------------------------------------------------------

    prompt = f"""
Create a high-retention short-form video script about:

{topic}

The requested video duration is exactly {duration} seconds.

The narration should contain approximately {word_count} spoken words.

Requirements:

- Start with a strong hook.
- Keep the viewer engaged throughout.
- Use natural spoken language.
- Use short and clear sentences.
- Make the information interesting and easy to understand.
- Do not include camera directions.
- Do not include scene directions.
- Do not include sound effects.
- Do not include timestamps.
- Do not include production instructions.
- Do not mention that the script was generated by AI.
- End naturally.

Return ONLY valid JSON in exactly this structure:

{{
    "script": "complete narration script",
    "dialogue": [
        "first spoken sentence",
        "second spoken sentence",
        "third spoken sentence"
    ]
}}
"""

    # --------------------------------------------------------
    # OPENAI REQUEST
    # --------------------------------------------------------

    try:

        response = client.chat.completions.create(
            model=os.getenv(
                "OPENAI_SCRIPT_MODEL",
                "gpt-4o-mini",
            ),
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a professional short-form "
                        "video script writer specializing in "
                        "engaging social media videos."
                    ),
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
            temperature=0.8,
        )

    except Exception as exc:

        raise RuntimeError(
            f"OpenAI script generation failed: {exc}"
        ) from exc

    # --------------------------------------------------------
    # GET RESPONSE
    # --------------------------------------------------------

    if not response.choices:

        raise RuntimeError(
            "OpenAI returned no choices."
        )

    content = response.choices[0].message.content

    if not content:

        raise RuntimeError(
            "OpenAI returned an empty script."
        )

    content = clean_response(
        content
    )

    # --------------------------------------------------------
    # PARSE JSON
    # --------------------------------------------------------

    try:

        data = json.loads(
            content
        )

    except json.JSONDecodeError as exc:

        raise RuntimeError(
            "OpenAI returned invalid script JSON."
        ) from exc

    # --------------------------------------------------------
    # EXTRACT SCRIPT
    # --------------------------------------------------------

    script_text = str(
        data.get(
            "script",
            "",
        )
    ).strip()

    if not script_text:

        raise RuntimeError(
            "OpenAI returned no script text."
        )

    # --------------------------------------------------------
    # EXTRACT DIALOGUE
    # --------------------------------------------------------

    dialogue = data.get(
        "dialogue",
        [],
    )

    if not isinstance(
        dialogue,
        list,
    ):

        raise RuntimeError(
            "OpenAI returned an invalid dialogue format."
        )

    dialogue = [
        str(sentence).strip()
        for sentence in dialogue
        if str(sentence).strip()
    ]

    if not dialogue:

        raise RuntimeError(
            "OpenAI returned no dialogue."
        )

    # --------------------------------------------------------
    # RETURN RESULTS
    # --------------------------------------------------------

    return (
        script_text,
        dialogue,
    )